// Autogenerated by JSCompiler
// @JSOL v0.2.0 - CLI Arguments Parser
const $parseRawCliArgs = function($rawArgs) {
    const $options = JSOL.dict("source", "", "outDir", "", "target", "", "jsTarget", "", "jsPrefix", "", "jsSuffix", "", "phpTarget", "", "phpPrefix", "", "phpSuffix", "");
    const $count = JSOL.count($rawArgs);
    for (let $i = 0; $i < $count; $i = $i + 1) {
        const $arg = $rawArgs[$i];
        let $isFlag = false;
         $isFlag = $arg.indexOf("--") === 0; 
        
        if ($isFlag === true) {
            let $key = ""; let $val = "";
            
                const $clean = $arg.substring(2);
                const $eqIndex = $clean.indexOf("=");
                if ($eqIndex !== -1) { $key = $clean.substring(0, $eqIndex); $val = $clean.substring($eqIndex + 1); } else { $key = $clean; $val = "true"; }
            
            
            if ($key === "source") { $options["source"] = $val; }
            if ($key === "out-dir") { $options["outDir"] = $val; }
            if ($key === "target") { $options["target"] = $val; $options["jsTarget"] = $val; $options["phpTarget"] = $val; }
            if ($key === "js-target") { $options["jsTarget"] = $val; }
            if ($key === "js-prefix") { $options["jsPrefix"] = $val; }
            if ($key === "js-suffix") { $options["jsSuffix"] = $val; }
            if ($key === "php-target") { $options["phpTarget"] = $val; }
            if ($key === "php-prefix") { $options["phpPrefix"] = $val; }
            if ($key === "php-suffix") { $options["phpSuffix"] = $val; }
        }
    }
    return $options;
};