// Autogenerated by JSCompiler
// @JSOL v0.2.0 - Targets Configuration Normalizer
const $normalizeTargetsConfig = function($rawConfig) {
    const $jsConfig = JSOL.dict("default", "", "targets", JSOL.dict());
    const $phpConfig = JSOL.dict("default", "", "targets", JSOL.dict());
    if ($rawConfig === null) {
        return JSOL.dict("js", $jsConfig, "php", $phpConfig);
    }
    if (Object.prototype.hasOwnProperty.call($rawConfig, "js")) {
        $jsConfig["default"] = $rawConfig["js"]["default"] || "";
        $jsConfig["targets"] = $rawConfig["js"]["targets"] || JSOL.dict();
    }
    if (Object.prototype.hasOwnProperty.call($rawConfig, "php")) {
        $phpConfig["default"] = $rawConfig["php"]["default"] || "";
        $phpConfig["targets"] = $rawConfig["php"]["targets"] || JSOL.dict();
    }
    if (Object.prototype.hasOwnProperty.call($rawConfig, "default") && Object.prototype.hasOwnProperty.call($rawConfig, "targets")) {
        $jsConfig["default"] = $rawConfig["default"];
        $phpConfig["default"] = $rawConfig["default"];
        $jsConfig["targets"] = $rawConfig["targets"];
        $phpConfig["targets"] = $rawConfig["targets"];
    }
    return JSOL.dict("js", $jsConfig, "php", $phpConfig);
};