// Autogenerated by JSCompiler
// @JSOL v0.2.0 - Self-Hosted Compiler Lexer Module
const $maskSourceCode = function($sourceCode) {
    const $tokens = [];
    let $maskedCode = $sourceCode;
    
        let $tokenIndex = 0;
        const $patternStr = "(\"([^\"\\\\]|\\\\.)*\"|'([^'\\\\]|\\\\.)*'|\\`([^\\`\\\\]|\\\\.)*\\`|\\/\\*[\\s\\S]*?\\*\\/|\\/\\/[^\\n]*)";
        const $regex = new RegExp($patternStr, "g");
        $maskedCode = $sourceCode.replace($regex, function($match) {
            const $key = "__JSOL_TOKEN_" + $tokenIndex + "__";
            $tokens.push(JSOL.dict("key", $key, "value", $match));
            $tokenIndex = $tokenIndex + 1;
            return $key;
        });
    
    
    return JSOL.dict("maskedCode", $maskedCode, "tokens", $tokens);
};

const $unmaskSourceCode = function($maskedCode, $tokens) {
    let $restoredCode = $maskedCode;
    const $tokenCount = JSOL.count($tokens);
    for (let $i = 0; $i < $tokenCount; $i = $i + 1) {
        const $token = $tokens[$i];
        const $key = $token["key"];
        const $val = $token["value"];
        
            $restoredCode = $restoredCode.split($key).join($val);
        
        
    }
    return $restoredCode;
};