<?php
// Autogenerated by PHPCompiler
// @JSOL v0.2.0 - Self-Hosted Engine Orchestrator
$resolveWrappers = function($targetsConfig, $cliTargetFlag, $cliPrefixOverride, $cliSuffixOverride) {
    $prefix = "";
    $suffix = "";
    if (mb_strlen($cliPrefixOverride, "UTF-8") > 0 || mb_strlen($cliSuffixOverride, "UTF-8") > 0) {
        return JSOL::dict("prefix", $cliPrefixOverride, "suffix", $cliSuffixOverride);
    }
    if (mb_strlen($cliTargetFlag, "UTF-8") > 0) {
        if ($targetsConfig["targets"] !== null && $targetsConfig["targets"][$cliTargetFlag] !== null) {
            $targetObj = $targetsConfig["targets"][$cliTargetFlag];
            return JSOL::dict("prefix", $targetObj["prefix"], "suffix", $targetObj["suffix"]);
        }
    }
    $defaultPointer = $targetsConfig["default"];
    if ($defaultPointer !== null && mb_strlen($defaultPointer, "UTF-8") > 0) {
        if ($targetsConfig["targets"] !== null && $targetsConfig["targets"][$defaultPointer] !== null) {
            $defaultObj = $targetsConfig["targets"][$defaultPointer];
            return JSOL::dict("prefix", $defaultObj["prefix"], "suffix", $defaultObj["suffix"]);
        }
    }
    return JSOL::dict("prefix", "", "suffix", "");
};

$executeCompilationPipeline = function($sourceCode, $targetsConfig, $cliOptions) use ($maskSourceCode, $unmaskSourceCode, $auditPragma, $auditForbiddenPatterns, $compileToJS, $compileToPHP, $resolveWrappers) {


    $pragmaResult = $auditPragma($sourceCode);
    if ($pragmaResult["valid"] === false) {
        return JSOL::dict("success", false, "errors", $pragmaResult["errors"]);
    }

    $maskedData = $maskSourceCode($sourceCode);
    $maskedCode = $maskedData["maskedCode"];
    $tokens = $maskedData["tokens"];



    $patternResult = $auditForbiddenPatterns($maskedCode);
    if ($patternResult["valid"] === false) {
        return JSOL::dict("success", false, "errors", $patternResult["errors"]);
    }

    $jsTargetFlag = $cliOptions["jsTarget"];
    $jsPrefixArg = $cliOptions["jsPrefix"];
    $jsSuffixArg = $cliOptions["jsSuffix"];
    $jsWrappers = $resolveWrappers($targetsConfig["js"], $jsTargetFlag, $jsPrefixArg, $jsSuffixArg);

    $phpTargetFlag = $cliOptions["phpTarget"];
    $phpPrefixArg = $cliOptions["phpPrefix"];
    $phpSuffixArg = $cliOptions["phpSuffix"];
    $phpWrappers = $resolveWrappers($targetsConfig["php"], $phpTargetFlag, $phpPrefixArg, $phpSuffixArg);

    $compiledJS = $compileToJS($maskedCode, $jsWrappers["prefix"], $jsWrappers["suffix"]);
    $compiledPHP = $compileToPHP($maskedCode, $phpWrappers["prefix"], $phpWrappers["suffix"]);

    $finalJS = $unmaskSourceCode($compiledJS, $tokens);
    $finalPHP = $unmaskSourceCode($compiledPHP, $tokens);

    return JSOL::dict(
        "success", true,
        "js", $finalJS,
        "php", $finalPHP
    );
};