<?php
// Autogenerated by PHPCompiler
// @JSOL v0.2.0 - Self-Hosted JS Target Compiler
$compileToJS = function($maskedCode, $prefix, $suffix) {
    $processBlock = function($code, $keyword, $unwrap) {
        $result = $code;
        $continue = true;
        while ($continue === true) {
            $startIdx = -1;
            
             $startIdx = strpos($result, $keyword); if ($startIdx === false) $startIdx = -1; 
            
            if ($startIdx === -1) {
                $continue = false;
            } else {
                $openBrace = -1;
                
                 $openBrace = strpos($result, "{", $startIdx); if ($openBrace === false) $openBrace = -1; 
                
                if ($openBrace === -1) {
                    $continue = false;
                } else {
                    $braceCount = 1;
                    $closeBrace = -1;
                    $rLen = mb_strlen($result, "UTF-8");
                    for ($i = $openBrace + 1; $i < $rLen; $i = $i + 1) {
                        $char = "";
                        
                         $char = substr($result, $i, 1); 
                        if ($char === "{") { $braceCount = $braceCount + 1; }
                        if ($char === "}") { $braceCount = $braceCount - 1; }
                        if ($braceCount === 0) {
                            $closeBrace = $i;
                            break;
                        }
                    }
                    
                    if ($closeBrace === -1) {
                        $continue = false;
                    } else {
                        $endIdx = $closeBrace + 1;
                        $findingEnd = true;
                        while ($endIdx < $rLen && $findingEnd === true) {
                            $char = "";
                            
                             $char = substr($result, $endIdx, 1); 
                            if ($char === " " || $char === "\n" || $char === "\r" || $char === ")" || $char === ";") {
                                $endIdx = $endIdx + 1;
                            } else {
                                $findingEnd = false;
                            }
                        }
                        
                        $before = "";
                        $after = "";
                        
                        
                            $before = substr($result, 0, $startIdx);
                            $after = substr($result, $endIdx);
                        
                        
                        if ($unwrap === true) {
                            $inner = "";
                            
                             $inner = substr($result, $openBrace + 1, $closeBrace - $openBrace - 1); 
                            
                             $result = $before . $inner . $after; 
                        } else {
                            
                             $result = $before . $after; 
                        }
                    }
                }
            }
        }
        return $result;
    };

    $transformed = $maskedCode;
    
    $transformed = $processBlock($transformed, "JSOL.PHP", false);
    $transformed = $processBlock($transformed, "JSOL.JS", true);

    
    
        $transformed = preg_replace('/JSOL\\.use\\s*\\([\\s\\S]*?\\)\\s*;?/', "", $transformed);
        $transformed = preg_replace('/JSOL\\.count\\s*\\(\\s*(\\$[a-zA-Z0-9_]+)\\s*\\)/', '$1.length', $transformed);
        $transformed = preg_replace('/JSOL\\.len\\s*\\(\\s*(\\$[a-zA-Z0-9_]+)\\s*\\)/', '$1.length', $transformed);
        $transformed = preg_replace('/JSOL\\.hasKey\\s*\\(\\s*(.+?)\\s*,\\s*(.+?)\\s*\\)/', 'Object.prototype.hasOwnProperty.call($1, $2)', $transformed);
    

    $finalOutput = "";
    
     $finalOutput = $prefix . $transformed . $suffix; 
    return $finalOutput;
};