<?php
// Autogenerated by PHPCompiler
// @JSOL v0.2.0 - Self-Hosted Compiler Lexer Module
$maskSourceCode = function($sourceCode) {
    $tokens = [];
    $maskedCode = $sourceCode;
    
    
        $tokenIndex = 0;
        $pattern = '/("([^"\\\\]|\\\\.)*"|\'([^\'\\\\]|\\\\.)*\'|`([^`\\\\]|\\\\.)*`|\\/\\*[\\s\\S]*?\\*\\/|\\/\\/[^\\n]*)/';
        $maskedCode = preg_replace_callback($pattern, function($matches) use (&$tokens, &$tokenIndex) {
            $key = "__JSOL_TOKEN_" . $tokenIndex . "__";
            $tokens[] = ["key" => $key, "value" => $matches[0]];
            $tokenIndex = $tokenIndex + 1;
            return $key;
        }, $sourceCode);
    
    return JSOL::dict("maskedCode", $maskedCode, "tokens", $tokens);
};

$unmaskSourceCode = function($maskedCode, $tokens) {
    $restoredCode = $maskedCode;
    $tokenCount = count($tokens);
    for ($i = 0; $i < $tokenCount; $i = $i + 1) {
        $token = $tokens[$i];
        $key = $token["key"];
        $val = $token["value"];
        
        
            $restoredCode = str_replace($key, $val, $restoredCode);
        
    }
    return $restoredCode;
};