<?php
// Autogenerated by PHPCompiler
// @JSOL v0.1.5 - Self-Hosted Compiler Linter Module

$auditPragma = function($sourceCode) {
    $errors = [];
    $hasPragma = false;
    
    
        $hasPragma = (bool)preg_match('/^\\s*\\/\\/\\s*@?jsol\\b/i', $sourceCode);
    
    if ($hasPragma === false) {
        $errors[] = "Fatal: Missing MANDATORY @JSOL pragma on Line 1.";
    }
    return JSOL::dict("valid", count($errors) === 0, "errors", $errors);
};

$auditForbiddenPatterns = function($maskedCode) {
    $errors = [];
    $hasFunctionalMethods = false;
    
    
        $hasFunctionalMethods = (bool)preg_match('/\\.(map|filter|reduce|forEach|find)\\s*\\(/', $maskedCode);
    
    if ($hasFunctionalMethods === true) {
        $errors[] = "Linter Error: Functional array methods (.map, .filter, etc.) are FORBIDDEN. Use imperative for/while loops.";
    }
    $hasLengthProperty = false;
    
    
        $hasLengthProperty = (bool)preg_match('/\\.length\\b/', $maskedCode);
    
    if ($hasLengthProperty === true) {
        $errors[] = "Linter Error: Accessing .length is FORBIDDEN. Use JSOL.count() for arrays or JSOL.len() for strings.";
    }
    return JSOL::dict("valid", count($errors) === 0, "errors", $errors);
};