<?php
// Autogenerated by PHPCompiler
// @JSOL v0.2.0 - Self-Hosted PHP Target Compiler
$compileToPHP = function($maskedCode, $prefix, $suffix) {
    $processBlock = function($code, $keyword, $unwrap) {
        $result = $code;
        $continue = true;
        while ($continue === true) {
            $startIdx = -1;
            
             $startIdx = strpos($result, $keyword); if ($startIdx === false) $startIdx = -1; 
            
            if ($startIdx === -1) {
                $continue = false;
            } else {
                $openBrace = -1;
                
                 $openBrace = strpos($result, "{", $startIdx); if ($openBrace === false) $openBrace = -1; 
                
                if ($openBrace === -1) {
                    $continue = false;
                } else {
                    $braceCount = 1;
                    $closeBrace = -1;
                    $rLen = mb_strlen($result, "UTF-8");
                    for ($i = $openBrace + 1; $i < $rLen; $i = $i + 1) {
                        $char = "";
                        
                         $char = substr($result, $i, 1); 
                        if ($char === "{") { $braceCount = $braceCount + 1; }
                        if ($char === "}") { $braceCount = $braceCount - 1; }
                        if ($braceCount === 0) {
                            $closeBrace = $i;
                            break;
                        }
                    }
                    
                    if ($closeBrace === -1) {
                        $continue = false;
                    } else {
                        $endIdx = $closeBrace + 1;
                        $findingEnd = true;
                        while ($endIdx < $rLen && $findingEnd === true) {
                            $char = "";
                            
                             $char = substr($result, $endIdx, 1); 
                            if ($char === " " || $char === "\n" || $char === "\r" || $char === ")" || $char === ";") {
                                $endIdx = $endIdx + 1;
                            } else {
                                $findingEnd = false;
                            }
                        }
                        
                        $before = "";
                        $after = "";
                        
                        
                            $before = substr($result, 0, $startIdx);
                            $after = substr($result, $endIdx);
                        
                        
                        if ($unwrap === true) {
                            $inner = "";
                            
                             $inner = substr($result, $openBrace + 1, $closeBrace - $openBrace - 1); 
                            
                             $result = $before . $inner . $after; 
                        } else {
                            
                             $result = $before . $after; 
                        }
                    }
                }
            }
        }
        return $result;
    };

    $transformed = $maskedCode;
    
    $transformed = $processBlock($transformed, "JSOL.JS", false);
    $transformed = $processBlock($transformed, "JSOL.PHP", true);

    
    
        $prefixes = ["\n", "\r\n", "\t", " ", "("];
        for ($p = 0; $p < 5; $p = $p + 1) {
            $transformed = str_replace($prefixes[$p] . "const ", $prefixes[$p], $transformed);
            $transformed = str_replace($prefixes[$p] . "let ", $prefixes[$p], $transformed);
            $transformed = str_replace($prefixes[$p] . "var ", $prefixes[$p], $transformed);
        }
        if (strpos($transformed, "const ") === 0) { $transformed = substr($transformed, 6); }
        if (strpos($transformed, "let ") === 0) { $transformed = substr($transformed, 4); }
        if (strpos($transformed, "var ") === 0) { $transformed = substr($transformed, 4); }

        $transformed = preg_replace('/(\\$[a-zA-Z0-9_]+)\\.push\\((.*?)\\)/', '$1[] = $2', $transformed);
        $transformed = str_replace('Math.PI', 'M_PI', $transformed);
        $transformed = str_replace('Math.', "", $transformed);
        $transformed = str_replace('isNaN(', 'is_nan(', $transformed);

        $transformed = preg_replace('/function\\s*\\((.*?)\\)\\s*\\{\\s*((?:__JSOL_TOKEN_\\d+__\\s*)*)JSOL\\.use\\s*\\((.*?)\\)\\s*;?/', "function($1) use ($3) {\n$2", $transformed);
        $transformed = preg_replace('/JSOL\\.count\\s*\\(/', 'count(', $transformed);
        $transformed = preg_replace('/JSOL\\.len\\s*\\(\\s*([^)]+?)\\s*\\)/', 'mb_strlen($1, "UTF-8")', $transformed);
        $transformed = preg_replace('/JSOL\\.hasKey\\s*\\(\\s*(.+?)\\s*,\\s*(.+?)\\s*\\)/', 'isset($1[$2])', $transformed);
        
        $transformed = str_replace('JSOL.', 'JSOL::', $transformed);
    

    $finalOutput = "";
    
     
        $finalOutput = $prefix . $transformed . $suffix; 
        if (strpos($finalOutput, "<?php") === false) {
            $finalOutput = "<?php\n" . $finalOutput;
        }
    
    return $finalOutput;
};